server:
  port: 9090

spring:
  application:
    name: msvc-product
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:users_db
    username: sa
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console.enabled: true 
logging:
  level:
    org:
      springframework:
        security: TRACE

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      