eureka:
  cliente:
    register-with-eureka: false
server:
  port: 8081

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8080
          predicates:
           - Path=/user/**
        - id: products
          uri: http://localhost:9090
          predicates:
           - Path=/product/**
        - id: typeProducts
          uri: http://localhost:9090
          predicates:
           - Path=/typeProduct/**
