server:
  port: 8081

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users-service
          uri: http://localhost: 8090
          predicates:
           - Path=/user/**
        - id: products-service
          uri: http://localhost: 9090
          predicates:
           - Path=/product/**
        - id: typeProducts-service
          uri: http://localhost: 9090
          predicates:
           - Path=/typeProduct/**
        - id: auth-service
          uri: http://localhost: 8088
          predicates:
           - Path=/auth/**
eureka:
  cliente:
    register-with-eureka: false