server:
  port: 8083

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://msvc-auth
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://msvc-user
          predicates:
            - Path=/user/**
        - id: product-service
          uri: lb://msvc-product
          predicates:
            - Path=/product/**
        - id: typeProduct-service
          uri: lb://msvc-product
          predicates:
            - Path=/typeProduct/**
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/